name: Trigger auto deployment for ca-python-source-lab

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CAPYTHONSOURCELAB_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CAPYTHONSOURCELAB_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CAPYTHONSOURCELAB_AZURE_SUBSCRIPTION_ID }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}

          registryUrl: ${{ secrets.CAPYTHONSOURCELAB_REGISTRY_URL }}
          registryUsername: ${{ secrets.CAPYTHONSOURCELAB_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CAPYTHONSOURCELAB_REGISTRY_PASSWORD }}

          containerAppName: ca-python-source-lab
          resourceGroup: rg-containerapp-source-lab

          imageToBuild: acrcapythonsourcelab01.azurecr.io/ca-python-source-lab:${{ github.sha }}

          targetPort: 8080
